site:
  title: Jakarta EE Documentation
  start_page: jakarta-ee-docs::index.adoc

content:
  # branches will be updated when PRs are merged
  sources:
  - url: https://github.com/virtua-tech/jakartaee-tutorial.git
    start_paths:
      - src/main/antora
    branches:
      - release/8
  - url: https://github.com/virtua-tech/jakartaee-tutorial.git
    start_paths:
      - src/main/docs
    branches:
      - antora-prototype-9.1
      - antora-prototype

urls:
  latest_version_segment: current

ui:
  bundle:
    url: https://github.com/virtua-tech/jakartaee-tutorial-ui/releases/download/latest/ui-bundle.zip
    snapshot: true

runtime:
  log:
    level: debug

antora:
  extensions:
  - '@antora/pdf-extension'
